API.md
src/parser.js
test/parse.test.js

*What:* Adds an `errorHandler` (function) argument to `parse`, which is called with the result object when there's an error. The default value for `errorHandler` is a function that throws an error.
*Why:* I want to use this for an eslint plugin to validate tagged groq queries in javascript, but it turns out that the error message `"Syntax error in GROQ query"` is not that helpful for large queries. The raw parser is more helpful (returning a `position`), but as far as I can tell the raw parser is not a part of the public API, so I'm not as comfortable using that directly. An error handler that exposes the `result` object from the raw parser solves this.
Here's an image for a bit more context (spot the typo!):

Add error handler to parser

---

src/evaluator/functions.js
src/evaluator/index.js
test/functions.test.js

This implements `now()` as-is. 
I'm curious if you think we should make this return a `dateTime`, or match the current behavior which returns an ISO-8601 timestamp?

Implement now() function (fixes #8)

---

src/evaluator/operators.ts

`[1] + [2]` is currently resulting in `null`, whereas the spec says it should return `[1, 2]`.

Support concatenation of arrays

---

.babelrc
package.json
src/evaluator/value.ts
src/rawParser.js
tsdx.config.js

Had some real trouble getting the ESM bundle to work. 
- The `evaluator/value.ts` file is referencing `exports.NULL_VALUE`, which it shouldn't in typescript environment (probably an oversight on my part when converting to typescript)
- The raw parser being CommonJS leads to some unnecessary complications and "interop" modes
- tsdx is including the regenerator runtime, which is causing a pretty massive bundle as well as several references to `module.exports`
This PR:
- Switches to using ESM-style exports of the two exported functions in the raw parser - hope that's ok. Not sure what generates/generated this file, but maybe that should be fixed too.
- Uses the constants  `NULL_VALUE` and  `TRUE_VALUE` instead of referencing `exports.*`
- Adds a babelrc with browser and node.js target …

Fix ES Module build

---

.github/workflows/test.yml
.travis.yml
src/evaluator/functions.ts
test/generate.sh

I also ended up adding Node 10.x to the test matrix and discovered that the ordering function wasn't correctly implemented.

Switch to GitHub Actions for running tests

---

src/evaluator/dateHelpers.ts
src/evaluator/equality.ts
src/evaluator/functions.ts
src/evaluator/operators.ts
src/evaluator/ordering.ts
src/evaluator/value.ts
test/generate.js
test/generate.sh

Currently this does not round-trip the time offset (which currently is enforced by the spec).

Implement dateTime

---

README.md

John recorded a free intro course on GROQ that would be great to link to here for those that are interested.
Resource link:

update readme with free egghead course on GROQ

---

CHANGELOG.md
src/rawParser.js
tap-snapshots/test/parse.test.ts.test.cjs
test/parse.test.ts

Previously when we saw `{"foo"` we would immediately start parsing it as a field (`{"foo":123}`). This is not correct since it's possible to write `{"foo" == bar => {…}}`). This changes the logic to always parse it as a general expression and if it ends up being parsed as a literal string _then_ we invoke the logic for field.

Parse object expressions starting with string

---

src/evaluator/functions.ts
src/markProcessor.ts
src/nodeTypes.ts
src/parser.ts
test/parse.test.ts

[The GROQ spec](https://sanity-io.github.io/GROQ/draft/#sec-Selector) requires support for selector validation. This has yet to be added to `groq-js`. Selector validation is a pre-requisite to supporting the `diff` and `delta` extensions in `groq-js`.
Note that full selector syntax isn't available yet, we need to add support for tuples and groups when parsing traversals.
* Add a `SELECTOR_BUILDER` to the parser to handle selector validation
* Add relevant unit tests

feat: add validation for selector syntax

---

.github/workflows/test.yml
src/evaluator/evaluate.ts

The build failed locally for me due to this missing evaluator.
Also added `npm run build` to the CI to ensure that we don't break the build.

Fix build error related to selectors

---

package.json

I was testing the new functionality inside another project (GROQ Arcade). The project wouldn't build and was erroring at runtime. It turns out Webpack is _very_ fussy about certain things, like whether the 'default' for exports is last in the list or not.
Changing the order fixes the issue. As far as I can tell this shouldn't negatively impact other builds/projects, so I think we should include the change in `main` and a new release candidate.

fix: ensure 'default' export path is specified last 

---

package.json

The runtime support for `groq-js` is really [good](https://groq-runtimes-dashboard.sanity.build/).
Except in esm.sh, a popular ESM CDN used a lot by Deno folks:
```js
const {parse} = await import('https://esm.sh/groq-js')
// throws error:
// VM1039:1          GET https://esm.sh/groq-js@1.1.0 net::ERR_ABORTED 500
// (anonymous) @ VM1039:1
// Uncaught TypeError: Failed to fetch dynamically imported module: https://esm.sh/groq-js
```
Opening the [ESM url](https://esm.sh/groq-js@1.1.0) directly gives a more helpful error:
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: Package path . is not exported from package /tmp/esm-build-215895dbb9a524568745e07124b861740c47353e-565f8556/node_modules/groq-js (see exports field in …
```

fix: build errors on esm.sh

---

src/evaluator/constantEvaluate.ts
test/parse.test.ts

In queries like *[(type == "book")] we didn't properly recurse to determine if it's possible constant evaluate the expression.

Handle parenthesis directly inside filters

---

.gitignore
src/1.ts
src/evaluator/evaluate.ts
src/evaluator/types.ts
test/evaluate.test.ts
test/testUtils.ts

Adding an optional `dereference` function to `evaluate` options as discussed in https://github.com/sanity-io/groq-js/pull/93
Some things I was wondering while working on this:
- Technically speaking we could return a document in this function which does not exist in the dataset at all. Is this something to address?
- Shall the `dereference` function receive the `dataset` (original or after `fromJS` transformation) as a second parameter, so it can be used when doing the lookup?
- We agreed to use `PromiseLike<Document | null>` as return value, but having this function as async isn't necessary needed. Shall we add support for sync return value as well?

Adding option to provide a custom dereference function

---

src/1.ts

For similar reason as #151, I need the `Path` class exported for [`@sanity-typed/groq-js`](https://github.com/saiichihashimoto/sanity-typed/tree/main/packages/groq-js)

feat: export Path class

---

src/typeEvaluator/evaluateQueryType.ts
src/typeEvaluator/optimizations.ts
src/typeEvaluator/scope.ts
src/typeEvaluator/types.ts
tap-snapshots/test/evaluateQueryType.test.ts.test.cjs
test/evaluateQueryType.test.ts

This removes Document as a TypeNode, keeping the api surface smaller and more actual type oriented

Remove document as a typenode and improve logging

---

src/typeEvaluator/evaluateQueryType.ts
src/typeEvaluator/functions.ts
src/typeEvaluator/index.ts
src/typeEvaluator/optimizations.ts
src/typeEvaluator/satisfies.ts
src/typeEvaluator/scope.ts
src/typeEvaluator/types.ts
tap-snapshots/test/evaluateQueryType.test.ts.test.cjs
test/evaluateQueryNode.test.ts
test/evaluateQueryType.test.ts

The code comment should explain the approach pretty well.
Note that currently the tests fail with:
```
Suites:   1 failed, 1 of 1 completed
Asserts:  26344 failed, 10172 passed, of 36516
```
It's maybe a bit too much, especially since this only covers `OpCall` and `AccessAttribute`.
I was thinking of extending this to all the different node types that we want to support initially.

test(typeEvaluator): add more fine-grained tests

---

package.json
src/typeEvaluator/index.ts

@sgulseth I noticed that the `typesVersions` array includes `typeEvaluator`.
However the file it refers to doesn't exist:
```
./dist/typeEvaluator/index.d.ts
```
Removing it in this PR as `import {typeEvaluate} from 'groq'` is how it's intended to be used.
I've also enabled reporting missing tsdoc release tags (seen when running `npm run prepublishOnly`) as I've seen some inconsistencies:
```bash
dist/__tmp__/src/evaluator/functions.d.ts:16:1 - warning ae-missing-release-tag
"GroqPipeFunction" is part of the package's API, but it is missing a release tag (@alpha, @beta, @public, or @internal)
dist/__tmp__/src/evaluator/scope.d.ts:3:1 - warning ae-missing-release-tag
"Scope" is part of the package's API, but it is missing a release tag (@alpha, @beta, @public, or @internal) …
```

fix: remove typeEvaluator typesVersions export

---

src/typeEvaluator/typeEvaluate.ts
tap-snapshots/test/typeEvaluate.test.ts.test.cjs
test/typeEvaluate.test.ts

If a condition resolves to `undefined` it means that we can't know wether the condition is true or false, for example this might be if we are using a parameter. This change appends the undefined resolved conditions as optional attributes to the resulting type

feat(typeEvaluation): let optional resolved condition be evaulated

---

src/typeEvaluator/typeEvaluate.ts
test/typeEvaluate.test.ts

Change the logic for comparing equality to be the same if we are comparing nodes in an union

Loosen strictness for equality with unions

---

src/typeEvaluator/typeEvaluate.ts
test/typeEvaluate.test.ts

If you do a query which might return null, we get a union with null, and we then attempt to filter on it we currently return `null` since we dont support comparing unions.

fix(typeEvaluation): map over unions to support filtering null-unions

---

src/typeEvaluator/functions.ts
src/typeEvaluator/typeEvaluate.ts
src/typeEvaluator/typeHelpers.ts
tap-snapshots/test/typeEvaluate.test.ts.test.cjs
test/typeEvaluate.test.ts

* Adds support for `count(ARRAY)`
* Added a `resolveUnionType` which recursively runs the resolver on each type inside unions, same as `mapUnion`
if ok, i'll merge and then refactor mapUnion in a separate PR

feat(typeEvaluation): add support for global::count

---

src/typeEvaluator/typeEvaluate.ts

* Removes `mapUnion`
* Handle cases where you could be comparing `inline` types

chore(typeEvaluation): use mapConcrete when handling opCalls

---

src/typeEvaluator/functions.ts
test/typeEvaluate.test.ts

Low hanging fruit, always returns a string.

feat(typeEvaluator): add support for global::now() and dateTime::now()

---

src/typeEvaluator/typeEvaluate.ts
tap-snapshots/test/typeEvaluate.test.ts.test.cjs
test/typeEvaluate.test.ts

When resolving filters we are creating a temporarily hidden scope for each node in the current scope. Since hidden parents are only ignored when creating a new nestedScope(non-hidden) we end up counting the hidden scope.
Fixes sanity-io/sanity#6635

Make sure we are not inside a hidden scope when resolving parent nodes

---

src/typeEvaluator/optimizations.ts
src/typeEvaluator/typeEvaluate.ts
src/typeEvaluator/typeHelpers.ts
tap-snapshots/test/typeEvaluate.test.ts.test.cjs
test/typeEvaluate.test.ts
test/typeEvaluateObjects.test.ts

When splatting an object we didn't map over the rest property, if it's an object we should append the attributes. If `rest` is unknown we should treat the entire object as unknown.
Fixes https://github.com/sanity-io/sanity/issues/6555

fix(typeEvlauator): handle rest on object splat operations

---

src/evaluator/functions.ts
src/typeEvaluator/functions.ts
test/evaluate.test.ts
test/typeEvaluate.test.ts

Add a new function `sanity::versionOf()` which lists all the stored document IDs that are a version of given published document ID in arg.

Add support for sanity::versionOf()

---

src/typeEvaluator/typeEvaluate.ts
test/typeEvaluate.test.ts
test/typeEvaluateObjects.test.ts

an optional attribute gets expanded into an union [attributeValue, null], since we were returning unknown for any nodes that werent an object the null value made the entire object unknown.

fix(typeEvaluator): fix bug when splatting over optional attributes

---

src/evaluator/functions.ts
src/typeEvaluator/functions.ts
test/evaluate.test.ts
test/typeEvaluate.test.ts

Add a new function `sanity::documentsOf()` which lists all the document IDs that are part of a given bundle ID in arg.

Add support for sanity::documentsOf()

---

src/typeEvaluator/booleans.ts
src/typeEvaluator/functions.ts
src/typeEvaluator/matching.ts
src/typeEvaluator/typeEvaluate.ts
src/typeEvaluator/typeHelpers.ts
tap-snapshots/test/typeEvaluate.test.ts.test.cjs
test/typeEvaluate.test.ts
test/typeEvaluateCompare.test.ts

Two changes included in this PR:
* Removes resolveCondition so that we can reuse types that are walked when we are resolving filters.
* Introduces BooleanInterpretation that can be used to determine boolean conditions

Remove resolve condition, use walk to determine conditions

---

src/typeEvaluator/functions.ts
src/typeEvaluator/typeEvaluate.ts
src/typeEvaluator/typeHelpers.ts

This PR changes so that mapConcrete also returns `unknown`, then it's up to the caller to handle these cases. Most notable this let us do unions of `null`/expectedType when unknown given

Handle unknowns

---

src/typeEvaluator/functions.ts
src/typeEvaluator/typeEvaluate.ts
src/typeEvaluator/typeHelpers.ts

mapNode is more precise as it doesn't always return a concrete type any more

Rename mapconcrete to mapnode

---

src/parser.ts
tap-snapshots/test/parse.test.ts.test.cjs
test/parse.test.ts

Need to make sure we align with https://sanity-io.github.io/GROQ/draft/#DetermineName()

feat: can extract attribute key from Group

---

src/typeEvaluator/functions.ts
tap-snapshots/test/typeEvaluate.test.ts.test.cjs
test/typeEvaluate.test.ts

We weren't really handling coalesce well:
1. We were pushing `null` into the list of possible types
2. We weren't handling unknowns
3. Even if we encountered a node that could never be null due to non-optional or no nulls in union we were still continuing
Opted to remove the snapshot and rather be explicit

fix: ensure coalesce handles optional/unknown/null properly

---

src/evaluator/functions.ts
test/parse.test.ts

Added support for text::query(). This is purely for making the parser not throw then the function is used, as groq-js itself does not have an actual search engine. 
Added a single test for making sure usage does not throw. 
Note: I am completely new to the groq-js codebase - let me know if there is something I'm missing.

feat: add support for text::query()

---

src/typeEvaluator/typeEvaluate.ts
test/typeEvaluate.test.ts

Map before resolving references to handle case where an inline type contains reference(s)
Added a few tests

fix(typeEvaluator): map derefs to handle inlined references

---

src/evaluator/functions.ts
src/typeEvaluator/functions.ts
src/typeEvaluator/typeHelpers.ts
tap-snapshots/test/typeEvaluate.test.ts.test.cjs
test/parse.test.ts
test/typeEvaluate.test.ts

The geo function is part of the spec as an extension, but is not included as part of groq-js. This makes groq-js non-compliant in accordance with the spec with extensions. This is especially problematic in places where groq-js is relied upon to safely parse queries but not evaluate anything, eg. sanity codegen.
As functions in the text namespace are already implemented with noops to not break the parser, I have done the same for all functions in the geo namespace.
Although not a complete implementation, this is miles better than today, as the parser actually works on groq queries used in production code today. This means that projects using these features finally can at least somewhat rely on tools requiring groq-js to parse queries.
I have tested this change together with `@sanity/cli` …

Add geo namespace with noop

---

src/parser.ts
src/rawParser.d.ts
src/rawParser.js
test/parse.test.ts

When the parser encounters a syntax error, we now return a message indicating what was wrong. This should be helpful in diagnosing problems and debugging issues.
Ensure all errors correctly describe the problem and are grammatically correct and understandable.
Unit tests should verify each type of error returns the expected error message.

feat: Add parser error messages

---

src/evaluator/functions.ts
src/evaluator/keyPath.ts
src/values/StreamValue.ts
test/evaluator/keyPath.test.ts
test/functions.test.ts

This PR enables the diff::changedOnly function
Ensure the algorithm matches expectations compared to the current implementation.
Added tests for new key path logic as well as tests for changedOnly which were verified against a dataset using the Vision tool.

feat: Add support for diff::changedOnly

---

src/values/StreamValue.ts
test/values/StreamValue.test.ts

If an error is thrown during the execution of the `fetch` function then node will kill the process due to an unhandled rejection. This PR handles the rejection by sending it to the current ticker's promise as a rejection.
Ensure StreamValues still work as expected to manage async generators.
Added a new test to ensurethe success and failure paths are handled as expected

fix: Handle exceptions during StreamValue fetch
